SELECT * FROM IMAGE;
SELECT * FROM MEMBER;
SELECT * FROM BOARD;
SELECT * FROM REPLY;
SELECT * FROM BLIKE;
SELECT * FROM REPORT;

TRUNCATE BOARD; 
TRUNCATE MEMBER; 

/*
 * 이미지 데이터 
 */
INSERT INTO IMAGE (TARGET_NO, TYPE_NO, I_NM) VALUES(7, 201, 'pic01.jpg'); -- 보드 7번 글 대표 이미지
INSERT INTO IMAGE (TARGET_NO, TYPE_NO, I_NM) VALUES(7, 202, 'pic02.jpg'); -- 보드 7번 글 이미지
INSERT INTO IMAGE (TARGET_NO, TYPE_NO, I_NM) VALUES(7, 203, 'pic03.jpg'); -- 보드 7번 글 이미지

INSERT INTO IMAGE (TARGET_NO, TYPE_NO, I_NM) VALUES(2, 201, 'pic01.jpg'); -- 보드 2번 글 이미지

INSERT INTO IMAGE (TARGET_NO, TYPE_NO, I_NM) VALUES(5, 201, 'cat.jpg'); -- 보드 5번 글 이미지

INSERT INTO IMAGE (TARGET_NO, TYPE_NO, I_NM) VALUES(101, 101, 'food1.jpg'); -- 상품 101번 대표 이미지
INSERT INTO IMAGE (TARGET_NO, TYPE_NO, I_NM) VALUES(101, 102, 'food1detail.jpg'); -- 상품 101번 대표 이미지
INSERT INTO IMAGE (TARGET_NO, TYPE_NO, I_NM) VALUES(102, 101, 'sand1.jpg'); -- 상품 102번 대표 이미지
INSERT INTO IMAGE (TARGET_NO, TYPE_NO, I_NM) VALUES(102, 102, 'sand1detail.jpg'); -- 상품 102번 대표 이미지
INSERT INTO IMAGE (TARGET_NO, TYPE_NO, I_NM) VALUES(103, 101, 'treat1.jpg'); -- 상품 103번 대표 이미지
INSERT INTO IMAGE (TARGET_NO, TYPE_NO, I_NM) VALUES(103, 102, 'treat1detail.jpg'); -- 상품 103번 대표 이미지
INSERT INTO IMAGE (TARGET_NO, TYPE_NO, I_NM) VALUES(104, 101, 'treat2.jpg'); -- 상품 104번 대표 이미지
INSERT INTO IMAGE (TARGET_NO, TYPE_NO, I_NM) VALUES(104, 102, 'treat2detail.jpg'); -- 상품 104번 대표 이미지

INSERT INTO IMAGE (TARGET_NO, TYPE_NO, I_NM) VALUES(105, 101, 'food2.jpg'); -- 상품 105번 대표 이미지
INSERT INTO IMAGE (TARGET_NO, TYPE_NO, I_NM) VALUES(106, 101, 'food3.jpg'); -- 상품 106번 대표 이미지
INSERT INTO IMAGE (TARGET_NO, TYPE_NO, I_NM) VALUES(107, 101, 'food4.jpg'); -- 상품 107번 대표 이미지
INSERT INTO IMAGE (TARGET_NO, TYPE_NO, I_NM) VALUES(108, 101, 'food5.jpg'); -- 상품 108번 대표 이미지
INSERT INTO IMAGE (TARGET_NO, TYPE_NO, I_NM) VALUES(109, 101, 'sand2.jpg'); -- 상품 109번 대표 이미지
INSERT INTO IMAGE (TARGET_NO, TYPE_NO, I_NM) VALUES(110, 101, 'sand3.jpg'); -- 상품 110번 대표 이미지

/*
 * 회원 데이터
 */
INSERT INTO MEMBER
(M_ID, M_PW, M_NM, CAT_NM, PHONE_NO, `ROLE`, POST_NO, ADDRESS1, ADDRESS2)
VALUES('abc123', '1234', '김회원', '냥이', '01000000000', 'MEMBER', '01234', '서울 노원구 공릉로 10길 123', '1234호');

INSERT INTO MEMBER
(M_ID, M_PW, M_NM, CAT_NM, PHONE_NO, `ROLE`, POST_NO, ADDRESS1, ADDRESS2)
VALUES('hong', '1234', '홍길동', '동글이', '01011111111', 'MEMBER', '02222', '서울 종로구 300-22', '101호');

INSERT INTO MEMBER
(M_ID, M_PW, M_NM, CAT_NM, PHONE_NO, `ROLE`, POST_NO, ADDRESS1, ADDRESS2)
VALUES('kang', '1234', '강문영', '냥이', '01022222222', 'MEMBER', '03333', '서울 강남구 테헤란로 12길', null);

INSERT INTO MEMBER
(M_ID, M_PW, M_NM, CAT_NM, PHONE_NO, `ROLE`, POST_NO, ADDRESS1, ADDRESS2)
VALUES('kim', '1234', '김길동', '김냥이', '01033333333', 'MEMBER', '04444', '서울 송파구 백제고분로 123길', '109동 1004호');

INSERT INTO MEMBER
(M_ID, M_PW, M_NM, CAT_NM, PHONE_NO, `ROLE`, POST_NO, ADDRESS1, ADDRESS2)
VALUES('cho', '1234', '조수빈', '나만없다', '01044444444', 'MEMBER', '05555', '서울 노원구 공릉로 100길', '202호');

/*
 * 게시판 데이터
 */
INSERT INTO BOARD
(M_NO, B_TITLE, B_CONTENT)
VALUES(100, '안녕하세요', '처음뵙겠습니다.');

INSERT INTO BOARD
(M_NO, B_TITLE, B_CONTENT)
VALUES(100, '고양이 좀 보세요', '길에서 만났어요');

INSERT INTO BOARD
(M_NO, B_TITLE, B_CONTENT)
VALUES(100, 'this is title', 'this is content');

INSERT INTO BOARD
(M_NO, B_TITLE, B_CONTENT)
VALUES(101, '고양아 안녕!!', '너무 귀엽죠?');

INSERT INTO BOARD
(M_NO, B_TITLE, B_CONTENT)
VALUES(102, '귀여운 사진 보고가요', '길냥이인데 너무 귀여워요!!');

INSERT INTO BOARD
(M_NO, B_TITLE, B_CONTENT)
VALUES(102, '얘도 길냥이', '이전 글에 올린 애랑 형제인가봐요');

INSERT INTO BOARD
(M_NO, B_TITLE, B_CONTENT)
VALUES(103, '이거 올리려고 가입했습니다..', 'ㅋㅋㅋ 똥배 보세요');

INSERT INTO BOARD
(M_NO, B_TITLE, B_CONTENT)
VALUES(104, '저는 고양이가 없습니다.', '님들아 너무 자랑하지 마세요 빡치니까.');

INSERT INTO BOARD
(M_NO, B_TITLE, B_CONTENT)
VALUES(104, '길냥이ㅋ', '아무리 봐도 저한테 관심있는 냥이 같죠?');


/*
 * 댓글 데이터
 */
INSERT INTO REPLY
(B_NO, M_NO, PARENT_NO, RE_CONTENT, RE_STEP)
VALUES(1, 101, null, '안녕하세요 저도 어제 가입했어요.', 1);

INSERT INTO REPLY
(B_NO, M_NO, PARENT_NO, RE_CONTENT, RE_STEP)
VALUES(1, 100, 1, '반겨주시니 감사합니다!', 2);

INSERT INTO REPLY
(B_NO, M_NO, PARENT_NO, RE_CONTENT, RE_STEP)
VALUES(2, 103, null, '좀 귀엽네요!!!', 1);

INSERT INTO REPLY
(B_NO, M_NO, PARENT_NO, RE_CONTENT, RE_STEP)
VALUES(3, 104, null, 'ㅋ 빡치게 하지마셈;', 1);

INSERT INTO REPLY
(B_NO, M_NO, PARENT_NO, RE_CONTENT, RE_STEP)
VALUES(3, 103, 4, '님 왤케 시비 거세요.. 이 분 이상해요;; 신고해야겠어요.', 2);

INSERT INTO REPLY
(B_NO, M_NO, PARENT_NO, RE_CONTENT, RE_STEP)
VALUES(4, 103, null, '너무 귀여워요...', 1);

/*
 * 좋아요 데이터
 */
INSERT INTO BLIKE (B_NO, M_NO) VALUES(2, 102);
INSERT INTO BLIKE (B_NO, M_NO) VALUES(5, 102);
INSERT INTO BLIKE (B_NO, M_NO) VALUES(7, 102);
INSERT INTO BLIKE (B_NO, M_NO) VALUES(4, 103);
INSERT INTO BLIKE (B_NO, M_NO) VALUES(7, 103);

/*
 * 신고 데이터
 * 		C : Board 게시글, 댓글 대댓글 신고
 * 		TARGET_NO 에는 게시글 PK 혹은 댓글 PK가 들어가야 함
 *		RP_STEP = 0(글), 1(댓글), 2(대댓글)
 */
INSERT INTO REPORT (TARGET_NO, RP_STEP, M_NO, RP_CONTENT)
VALUES(4, 1, 104, '시비성 댓글');

INSERT INTO REPORT (TARGET_NO, RP_STEP, M_NO, RP_CONTENT)
VALUES (4, 1, 104, '시비성 댓글');

INSERT INTO REPORT (TARGET_NO, RP_STEP, M_NO, RP_CONTENT)
VALUES (3, 0, 104, '시비성 댓글');


/*
 * PRODUCT (상품)
 * */

-- INSERT 
INSERT INTO PRODUCT
(P_NM, P_CATEGORY, P_PRICE, P_AMT, P_DETAIL, DC_PERCENT)
VALUES ('고양이 사료', 'food', 30000, 5, '전연령의 고양이가 먹을 수 있는 사료', 10);
INSERT INTO PRODUCT
(P_NM, P_CATEGORY, P_PRICE, P_AMT, P_DETAIL, DC_PERCENT)
VALUES ('kitten 사료', 'food', 45000, 5, '새끼 고양이가 먹을 수 있는 사료', 10);
INSERT INTO PRODUCT
(P_NM, P_CATEGORY, P_PRICE, P_AMT, P_DETAIL, DC_PERCENT)
VALUES ('비만고양이 사료', 'food', 50000, 5, '저지방 사료', 0);
INSERT INTO PRODUCT
(P_NM, P_CATEGORY, P_PRICE, P_AMT, P_DETAIL, DC_PERCENT)
VALUES ('유기농 사료', 'food', 35000, 5, '최고급 유기농 사료', 0);
INSERT INTO PRODUCT
(P_NM, P_CATEGORY, P_PRICE, P_AMT, P_DETAIL, DC_PERCENT)
VALUES ('고등어가 들어간 사료', 'food', 25000, 5, '고등어가 들어간 사료', 20);
INSERT INTO PRODUCT
(P_NM, P_CATEGORY, P_PRICE, P_AMT, P_DETAIL, DC_PERCENT)
VALUES ('고양이 모래', 'sand', 15000, 5, '부드러운 고양이 모래', 20);
INSERT INTO PRODUCT
(P_NM, P_CATEGORY, P_PRICE, P_AMT, P_DETAIL, DC_PERCENT)
VALUES ('두부 모래 10kg', 'sand', 25000, 5, '두부 입자 모래', 0);
INSERT INTO PRODUCT
(P_NM, P_CATEGORY, P_PRICE, P_AMT, P_DETAIL, DC_PERCENT)
VALUES ('벤토나이트 모래 5kg', 'sand', 17000, 5, '깔끔한 벤토 모래', 0);
INSERT INTO PRODUCT
(P_NM, P_CATEGORY, P_PRICE, P_AMT, P_DETAIL, DC_PERCENT)
VALUES ('고양이 간식', 'treat', 5000, 5, '기본 츄르', 0);
INSERT INTO PRODUCT
(P_NM, P_CATEGORY, P_PRICE, P_AMT, P_DETAIL, DC_PERCENT)
VALUES ('말린 황태', 'treat', 7000, 5, '한 달 동안 열심히 말려서 만든 황태', 5);

/*
 * ORDER
 */
SELECT * from `ORDER`;
SELECT od.*, p.P_CATEGORY, p.P_NM from ORDER_DETAIL od INNER JOIN PRODUCT p ON od.P_NO = p.P_NO ;
select * from PRODUCT p ;

-- 107(유기농 사료) 2개, 102(고양이 모래) 3개, 104(말린 황태) 2개 삼
INSERT INTO `ORDER`
(M_NO, RCV_NM, RCV_PHONE_NO, RCV_ADDRESS, O_PAY)
VALUES(102, '강문영', '01022222222', '(01234) 서울 강남구 테헤란로 12길', '카카오페이');
-- 107(유기농 사료) 2개
INSERT INTO ORDER_DETAIL
(O_NO, P_NO, OD_CNT, OD_PRICE)
VALUES(100, 107, 2, (SELECT (P_PRICE * (100 - DC_PERCENT)/100) FROM PRODUCT WHERE P_NO = 107) * 2);
-- 102(고양이 모래) 3개
INSERT INTO ORDER_DETAIL
(O_NO, P_NO, OD_CNT, OD_PRICE)
VALUES(100, 102, 3, (SELECT (P_PRICE * (100 - DC_PERCENT)/100) FROM PRODUCT WHERE P_NO = 102) * 3);
-- 104(말린 황태) 2개
INSERT INTO ORDER_DETAIL
(O_NO, P_NO, OD_CNT, OD_PRICE)
VALUES(100, 104, 2, (SELECT (P_PRICE * (100 - DC_PERCENT)/100) FROM PRODUCT WHERE P_NO = 104) * 2);


-- 101(고양이 사료) 1개, 109(두부 모래) 1개, 103(고양이 간식) 5개 삼
INSERT INTO `ORDER`
(M_NO, RCV_NM, RCV_PHONE_NO, RCV_ADDRESS, O_PAY)
VALUES(100, '김회원', '01000000000', '(01234) 서울 노원구 공릉로 10길 123', '카카오페이');
-- 101(고양이 사료) 1개
INSERT INTO ORDER_DETAIL
(O_NO, P_NO, OD_CNT, OD_PRICE)
VALUES(101, 101, 1, (SELECT (P_PRICE * (100 - DC_PERCENT)/100) FROM PRODUCT WHERE P_NO = 101) * 1);
-- 109(두부 모래) 1개
INSERT INTO ORDER_DETAIL
(O_NO, P_NO, OD_CNT, OD_PRICE)
VALUES(101, 109, 1, (SELECT (P_PRICE * (100 - DC_PERCENT)/100) FROM PRODUCT WHERE P_NO = 109) * 1);
-- 103(고양이 간식) 5개
INSERT INTO ORDER_DETAIL
(O_NO, P_NO, OD_CNT, OD_PRICE)
VALUES(101, 103, 5, (SELECT (P_PRICE * (100 - DC_PERCENT)/100) FROM PRODUCT WHERE P_NO = 103) * 5);


-- 109(두부 모래) 1개 삼
INSERT INTO `ORDER`
(M_NO, RCV_NM, RCV_PHONE_NO, RCV_ADDRESS, O_PAY)
VALUES(100, '김회원', '01000000000', '(01234) 서울 노원구 공릉로 10길 123', '카카오페이');
-- 109(두부 모래) 1개
INSERT INTO ORDER_DETAIL
(O_NO, P_NO, OD_CNT, OD_PRICE)
VALUES(102, 109, 1, (SELECT (P_PRICE * (100 - DC_PERCENT)/100) FROM PRODUCT WHERE P_NO = 109) * 1);


/*
 * 리뷰 데이터
 */

INSERT INTO REVIEW
(P_NO, M_NO, R_CONTENT, R_RATE)
VALUES(101, (SELECT M_NO FROM MEMBER WHERE M_ID = 'hyerin0508'), '사료가 맛 없어요', 3);

INSERT INTO REVIEW
(P_NO, M_NO, R_CONTENT, R_RATE
VALUES(102, (SELECT M_NO FROM MEMBER WHERE M_ID = 'seunguk0713'), '제 입맛에 딱이네요', 5);

INSERT INTO REVIEW
(P_NO, M_NO, R_CONTENT, R_RATE)
VALUES(103, (SELECT M_NO FROM MEMBER WHERE M_ID = 'junhyung'), '너무 맛있어요!', 5);

INSERT INTO REVIEW
(P_NO, M_NO, R_CONTENT, R_RATE)
VALUES(104, (SELECT M_NO FROM MEMBER WHERE M_ID = 'kotddari'), '한 번 가지고 놀고 안 가지고 놀아요', 2);

INSERT INTO REVIEW
(P_NO, M_NO, R_CONTENT, R_RATE)
VALUES(105, (SELECT M_NO FROM MEMBER WHERE M_ID = 'dlwjddk'), '이걸 장난감이라고 만든건가요?', 1);

INSERT INTO REVIEW
(P_NO, M_NO, R_CONTENT, R_RATE)
VALUES(106, (SELECT M_NO FROM MEMBER WHERE M_ID = 'moon0'), '우리 준형이가 잘 먹어요!!', 5);

INSERT INTO REVIEW
(P_NO, M_NO, R_CONTENT, R_RATE)
VALUES(107, (SELECT M_NO FROM MEMBER WHERE M_ID = 'junghee'), '나름 괜찮아요', 4);